workflows:
  openlineage-spec:
    jobs:
      - verify-spec-snapshot:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          context: << pipeline.parameters.build-context >>
      - workflow_complete:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}(-rc\.[0-9]+)?$/
          requires:
            - release-client-java
            - release-integration-sql-java